### ISSUE TITLE
Location of Meteor IP

### ISSUE THREAD

**Issue by mattprivman** [kenyee/MeteorPartiesDDPClient#1]
I've been looking for a while and seem unable to find the location of where you define demoparties.meteor.com. 

Where would I find it?

**Comment by mattprivman** [comment]
Nevermind, found it. It's defined in android-ddp-client, and you have to override it in order to change it.

**Comment by prathviraj080** [comment]
@mattppp how did you do that?

**Comment by mattprivman** [comment]
It's in @kenyee's other android-ddp-client repo: https://github.com/kenyee/android-ddp-client/blob/master/src/com/keysolutions/ddpclient/android/DDPStateSingleton.java

**Comment by kenyee** [comment]
Yep...sorry...override sMeteorServer or initInstance in the ddpstatesingleton
