### ISSUE TITLE
Unable to connect to server - Connection State = Closed

### ISSUE THREAD

**Issue by naXa777** [kenyee/MeteorPartiesDDPClient#4]
I've modified your DDPClientExample. I attempt to login with existing user credentials and receive Login Error. Please, help!

I create DDPStateSingleton with the following settings:

```
String meteorServer = "http://rapid-auto-37-209210.euw1.nitrousbox.com";
Integer meteorPort = 3000;
mInstance = new MyDDPState(context, meteorServer, meteorPort);
```

And then I perform a user login attempt:

```
MyDDPState.getInstance().login(mEmail, mPassword);
```

But I receive WebsocketNotConnectedException (it is throwed from `org.java_websocket.WebSocketImpl#send(String)`) so my login request ends with error message

   "Unknown websocket error (exception in callback?)"

Singleton state during exception:

```
mConnState = Closed
mMeteorServerAddress = ws://http://rapid-auto-37-209210.euw1.nitrousbox.com:3000/websocket
```

I see that connection is closed although `connectIfNeeded()` was called before.

**Comment by kenyee** [comment]
Paul: was this just user error?

**Comment by naXa777** [comment]
yes, it was my error. one of these silly typos...
see here for details http://stackoverflow.com/q/29309131/1429387

**Comment by naXa777** [comment]
though the exception message is very unclear. in my case the real cause has been contained inside the `cause` property: `UnresolvedAddressException` so I have wasted so much time on debugging.

**Comment by naXa777** [comment]
though the error message is very unclear. in my case the real cause has been contained inside the `cause` property: `UnresolvedAddressException`. and I have wasted so much time on debugging to find it.
